# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LRTq <- function(expr, geno, causal_ratio, perm = 1000L) {
    .Call(`_LRTq_LRTq`, expr, geno, causal_ratio, perm)
}

